// <auto-generated />
using System;
using MedicationOrders.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MedicationOrders.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20200608201028_seed")]
    partial class seed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MedicationOrders.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2020, 4, 2, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTime(2020, 4, 3, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("MedicationOrders.Models.Order", b =>
                {
                    b.OwnsMany("MedicationOrders.Models.OrderItem", "Items", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<int>("DaysSupply")
                                .HasColumnType("int");

                            b1.Property<string>("Frequency")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<int>("OrderId")
                                .HasColumnType("int");

                            b1.Property<int>("Quantity")
                                .HasColumnType("int");

                            b1.HasKey("Id");

                            b1.HasIndex("OrderId");

                            b1.ToTable("OrderItem");

                            b1.WithOwner()
                                .HasForeignKey("OrderId");

                            b1.HasData(
                                new
                                {
                                    Id = 1,
                                    DaysSupply = 30,
                                    Frequency = "Every Day",
                                    Name = "Collagen Dressing",
                                    OrderId = 1,
                                    Quantity = 30
                                },
                                new
                                {
                                    Id = 2,
                                    DaysSupply = 30,
                                    Frequency = "Every Day",
                                    Name = "Collagen Powder",
                                    OrderId = 1,
                                    Quantity = 30
                                },
                                new
                                {
                                    Id = 3,
                                    DaysSupply = 30,
                                    Frequency = "Every Day",
                                    Name = "WaterProof Tape",
                                    OrderId = 1,
                                    Quantity = 1
                                },
                                new
                                {
                                    Id = 10,
                                    DaysSupply = 30,
                                    Frequency = "Every Day",
                                    Name = "Collagen Dressing",
                                    OrderId = 2,
                                    Quantity = 30
                                },
                                new
                                {
                                    Id = 11,
                                    DaysSupply = 30,
                                    Frequency = "Once A Week",
                                    Name = "Botox",
                                    OrderId = 2,
                                    Quantity = 4
                                });
                        });

                    b.OwnsOne("MedicationOrders.Models.Patient", "Patient", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<int>("OrderId")
                                .HasColumnType("int");

                            b1.Property<string>("State")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("StreetAddress")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("ZipCode")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("Id");

                            b1.HasIndex("OrderId")
                                .IsUnique();

                            b1.ToTable("Orders1");

                            b1.WithOwner()
                                .HasForeignKey("OrderId");

                            b1.HasData(
                                new
                                {
                                    Id = 1,
                                    City = "Tampa",
                                    FirstName = "Kim",
                                    LastName = "Wise",
                                    OrderId = 1,
                                    State = "FL",
                                    StreetAddress = "1234 8th St.",
                                    ZipCode = "33606"
                                },
                                new
                                {
                                    Id = 2,
                                    City = "Tampa",
                                    FirstName = "Elvin",
                                    LastName = "Sharvill",
                                    OrderId = 2,
                                    State = "FL",
                                    StreetAddress = "567 Gulf Ave.",
                                    ZipCode = "33609"
                                });
                        });

                    b.OwnsOne("MedicationOrders.Models.Provider", "Provider", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<int>("OrderId")
                                .HasColumnType("int");

                            b1.HasKey("Id");

                            b1.HasIndex("OrderId")
                                .IsUnique();

                            b1.ToTable("Orders2");

                            b1.WithOwner()
                                .HasForeignKey("OrderId");

                            b1.HasData(
                                new
                                {
                                    Id = 1,
                                    Name = "Dr. Collins",
                                    OrderId = 1
                                },
                                new
                                {
                                    Id = 2,
                                    Name = "Dr. Collins",
                                    OrderId = 2
                                });
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
